name: Changelog

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "**/CHANGELOG.md"

jobs:
  if_merged:
    # This job will only run if the PR is merged and head branch is changeset-release/main
    if:
      ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == "changeset-release/main" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update changelog
        run: pnpm changelog --number={{ github.event.pull_request.number }}

      - name: Commit updates
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: sync changelog"
          author_name: Segun Adebayo
          author_email: joseshegs@gmail.com
